package report

import (
	"fmt"
	"html/template"
	"os"
)

// WriteHTML renders a self-contained static HTML report (no external
// assets, safe to open straight from disk or attach to a CI artifact).
// assertions may be nil if the scenario had none.
func WriteHTML(path string, r Result, assertions []AssertionResult) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("report: create %s: %w", path, err)
	}
	defer f.Close()

	data := htmlData{
		Result:      r,
		Assertions:  assertions,
		Duration:    formatDuration(r.Duration),
		Throughput:  formatFloat(r.Throughput),
		Total:       formatInt(r.TotalTransactions),
		SuccessRate: fmt.Sprintf("%.2f", r.SuccessRate),
		Reverted:    formatInt(r.RevertedTransactions),
		NonceErrors: formatInt(r.NonceErrors),
		RPCErrors:   formatInt(r.RPCErrors),
		GasAvg:      formatInt(int64(r.Gas.Average)),
		GasP95:      formatInt(int64(r.Gas.P95)),
		RPCP50:      formatDuration(r.RPCLatency.P50),
		RPCP95:      formatDuration(r.RPCLatency.P95),
		RPCP99:      formatDuration(r.RPCLatency.P99),
		TxP50:       formatDuration(r.TransactionLatency.P50),
		TxP95:       formatDuration(r.TransactionLatency.P95),
		TxP99:       formatDuration(r.TransactionLatency.P99),
	}

	if err := htmlTemplate.Execute(f, data); err != nil {
		return fmt.Errorf("report: render html: %w", err)
	}
	return nil
}

type htmlData struct {
	Result      Result
	Assertions  []AssertionResult
	Duration    string
	Throughput  string
	Total       string
	SuccessRate string
	Reverted    string
	NonceErrors string
	RPCErrors   string
	GasAvg      string
	GasP95      string
	RPCP50      string
	RPCP95      string
	RPCP99      string
	TxP50       string
	TxP95       string
	TxP99       string
}

var htmlTemplate = template.Must(template.New("report").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Web3Load Report{{if .Result.ScenarioName}} — {{.Result.ScenarioName}}{{end}}</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #0f1216; --panel: #171b21; --border: #262c35;
    --text: #e6e9ef; --muted: #8b95a5;
    --accent: #5b9dff; --good: #3fbf7f; --bad: #ef5a5a;
  }
  @media (prefers-color-scheme: light) {
    :root { --bg: #f5f6f8; --panel: #ffffff; --border: #e2e5ea; --text: #1c2128; --muted: #5b6472; }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 2.5rem 1.5rem; background: var(--bg); color: var(--text);
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  }
  .wrap { max-width: 880px; margin: 0 auto; }
  h1 { font-size: 1.4rem; margin: 0 0 0.25rem; }
  .subtitle { color: var(--muted); margin: 0 0 2rem; font-size: 0.9rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
  .tile { background: var(--panel); border: 1px solid var(--border); border-radius: 8px; padding: 1rem 1.2rem; }
  .tile .label { color: var(--muted); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em; }
  .tile .value { font-size: 1.6rem; margin-top: 0.3rem; }
  section { background: var(--panel); border: 1px solid var(--border); border-radius: 8px; padding: 1.2rem 1.4rem; margin-bottom: 1.5rem; }
  section h2 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); margin: 0 0 1rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.95rem; }
  td { padding: 0.35rem 0; }
  td:last-child { text-align: right; font-variant-numeric: tabular-nums; }
  .pass { color: var(--good); }
  .fail { color: var(--bad); }
  ul.assertions { list-style: none; margin: 0; padding: 0; }
  ul.assertions li { padding: 0.35rem 0; border-bottom: 1px solid var(--border); font-size: 0.9rem; }
  ul.assertions li:last-child { border-bottom: none; }
  .tag { display: inline-block; width: 3.5rem; font-weight: 600; }
</style>
</head>
<body>
<div class="wrap">
  <h1>Web3 Load Test{{if .Result.ScenarioName}}: {{.Result.ScenarioName}}{{end}}</h1>
  <p class="subtitle">Generated by web3load</p>

  <div class="grid">
    <div class="tile"><div class="label">Duration</div><div class="value">{{.Duration}}</div></div>
    <div class="tile"><div class="label">Transactions</div><div class="value">{{.Total}}</div></div>
    <div class="tile"><div class="label">Throughput</div><div class="value">{{.Throughput}} TPS</div></div>
    <div class="tile"><div class="label">Success Rate</div><div class="value">{{.SuccessRate}}%</div></div>
  </div>

  <section>
    <h2>RPC Latency</h2>
    <table>
      <tr><td>p50</td><td>{{.RPCP50}}</td></tr>
      <tr><td>p95</td><td>{{.RPCP95}}</td></tr>
      <tr><td>p99</td><td>{{.RPCP99}}</td></tr>
    </table>
  </section>

  <section>
    <h2>Transaction Latency</h2>
    <table>
      <tr><td>p50</td><td>{{.TxP50}}</td></tr>
      <tr><td>p95</td><td>{{.TxP95}}</td></tr>
      <tr><td>p99</td><td>{{.TxP99}}</td></tr>
    </table>
  </section>

  <section>
    <h2>Gas</h2>
    <table>
      <tr><td>average</td><td>{{.GasAvg}}</td></tr>
      <tr><td>p95</td><td>{{.GasP95}}</td></tr>
    </table>
  </section>

  <section>
    <h2>Errors</h2>
    <table>
      <tr><td>Reverted transactions</td><td>{{.Reverted}}</td></tr>
      <tr><td>Nonce errors</td><td>{{.NonceErrors}}</td></tr>
      <tr><td>RPC errors</td><td>{{.RPCErrors}}</td></tr>
    </table>
  </section>

  {{if .Assertions}}
  <section>
    <h2>Assertions</h2>
    <ul class="assertions">
      {{range .Assertions}}
      <li><span class="tag {{if .Passed}}pass{{else}}fail{{end}}">{{if .Passed}}PASS{{else}}FAIL{{end}}</span>{{.Expr}}</li>
      {{end}}
    </ul>
  </section>
  {{end}}
</div>
</body>
</html>
`))
